### ISSUE TITLE
Plugin using depricated function woocommerce_product_write_panels 

### ISSUE THREAD

**Issue by ChrisFreemanKY** [DPO-Group/DPO_WooCommerce#10]
Deprecated: woocommerce_product_write_panels is deprecated since version 2.6! Use Use woocommerce_product_data_panels action instead. instead. in C:\inetpub\wwwroot\WordsOnit\wp-includes\functions.php on line 5586

![image](https://user-images.githubusercontent.com/44512526/146230083-083b7f1b-2c09-40d6-80df-14f0f4b44ac7.png)

**Comment by bruce-atkinson** [comment]
@ChrisFreemanKY noted and will be integrated into the next release.


- add_action('woocommerce_product_write_panels', 'custom_tab_options');
+ add_action('woocommerce_product_data_panels', 'custom_tab_options');
