### ISSUE TITLE
$woothemes is undefined in global scope, causes errors

### ISSUE THREAD

**Issue by ChrisFreemanKY** [DPO-Group/DPO_WooCommerce#11]
$woothemes is not defined in a class and is not acessible in down page function, wrap it in a class and reference the class 

![image](https://user-images.githubusercontent.com/44512526/146230513-93d10a5c-b63d-4fc1-9c75-c6102603a57b.png)

**Comment by bruce-atkinson** [comment]
Hi @ChrisFreemanKY.

Please note this will be addressed in the next release.
