### ISSUE TITLE
DPO_WooCommerce-master 1.1.1 causing error

### ISSUE THREAD

**Issue by touche121** [DPO-Group/DPO_WooCommerce#13]
![Screenshot 2022-03-09 125056](https://user-images.githubusercontent.com/50205698/157428572-b7bff83f-4584-415a-a29a-c594eb4f4710.png)
Downloaded and installed the dpo plugin, once installing i get prompted to activate the plugin, which then fails to activate, giving out the message that the "plugin does not have a valid header" as on the above picture.

Then I tried to re-activate the plugin on the Installed Plugin page, which then moves to giving me an error as on the below picture. From there i will not be able to access my WordPress Admin dashboard and the website
![Screenshot 2022-03-09 125942](https://user-images.githubusercontent.com/50205698/157428713-8cd23301-f632-4f46-83dd-ee35230b3e5f.png)

here is more information for further reference 
WordPress version 5.9.1
Current theme: Astra (version 3.7.9)
Current plugin: DPO Group plugin for WooCommerce (version 1.1.1)
PHP version 8.0.16

**Comment by bruce-atkinson** [comment]
Hi @touche121,

Please kindly contact the DPO Group support team at https://dpogroup.com/contact-us/ should you require any assistance.
