### ISSUE TITLE
DPO Reference Numbers

### ISSUE THREAD

**Issue by bawby** [DPO-Group/DPO_WooCommerce#14]
Is it possible to have the plugin return the DPO reference number in woocommerce order like Paypal? Perhaps even making the number a link to the transaction on DPO's backend? As a developer, client may change DPO portal credentials hence it would make it easier to track as well as troubleshoot.
![Paypal Transaction screenshot](https://user-images.githubusercontent.com/6060137/165066208-9b5cd5bc-0c64-4f6d-8ef0-030275284dbe.jpeg)
.

**Comment by bruce-atkinson** [comment]
@bawby transaction reference will be included in the next release.


```
            // Add Transaction ID
            $transRef = $xml->TransRef[0]->__toString();
            $order = new WC_Order($order_id);
            $order->set_transaction_id($transRef);
            $order->save();

            // Add record to order - will appear as custom field in admin
            update_post_meta($order_id, 'dpo_reference', $xml->TransRef[0]->__toString());
            update_post_meta($order_id, 'dpo_reference', $transRef);
```
