### ISSUE TITLE
Issue with current version 1.1.2

### ISSUE THREAD

**Issue by habib3962** [DPO-Group/DPO_WooCommerce#16]
whenever i install 1.1.2 version i get critical errors when i activate the plugin.
before this version i installed dpo 1.1.0, that works perfectly fine.

I have php version 8.0, WooCommerce version 7.4.1 and WordPress version 6.1.1

in error log it shows
PHP Fatal error:  Uncaught Error: Call to undefined function is_plugin_inactive() in /home/domainname/public_html/wp-content/plugins/DPO_WooCommerce-master/gateway-direct-pay-online.php:32

add_to_cart_fragments is deprecated since version 3.0.0! Use woocommerce_add_to_cart_fragments instead.

**Comment by bruce-atkinson** [comment]
@habib3962, please kindly remove the DPO_WooCommerce-master folder from your plugins folder, and then install fresh using https://wordpress.org/plugins/dpo-group-for-woocommerce/ or by searching for 'DPO Pay' from the install new plugins window.
