### ISSUE TITLE
Incompatible with WooCommerce features

### ISSUE THREAD

**Issue by chuck189** [DPO-Group/DPO_WooCommerce#19]
Hi Team,

Just seen this in my plugins here for WooCommerce seems to be something that needs to be updated.

Regards
<img width="1234" alt="Screenshot 2023-12-16 at 5 23 09 PM" src="https://github.com/DPO-Group/DPO_WooCommerce/assets/64158289/55c2038e-203d-427f-bf87-4794aa440d91">

**Comment by bruce-atkinson** [comment]
Hi @chuck189,

Please note #20 https://github.com/DPO-Group/DPO_WooCommerce/releases/tag/v1.1.4, which attends to this issue.

**Comment by chuck189** [comment]
Much appreciated @appinlet
